---
title: "Trawl Data Wrangling"
author: "Cori Lopazanski"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Tidying Trawl Data

```{r}
# Attach Packages and Read in the Data
library(tidyverse)
library(janitor)

trawl_test <- read_csv("trawl_shiny_updated_21Feb2020.csv") %>% 
  clean_names()



```


Basic Trawl Data Wrangling - Get into tidy format silly data
```{r}
# Wrangling
trawl <- trawl_test %>% 
  select(tow_id, date, project, site, habitat:distance_m, depth_m:sal_ppt, num_aca_bah:wt_jellyfish) %>% 
  pivot_longer(num_aca_bah:wt_jellyfish,
               names_to = "names",
               values_to = "values") %>%
  separate(names,
           into = c("type", "genus", "species", "extra"),
           sep = "_") %>%
  unite(col = "species_name",
        genus:extra,
        sep = "_",
        na.rm = TRUE) %>%
  mutate(sp_id = rep(1:(length(values)/2), each = 2))  # create column identifying each individual species iteration (important for next step) 

# Create a widened dataframe so that number and weight have their own column
trawl_wide <- trawl %>%
  pivot_wider(id_cols = sp_id, names_from = type, values_from = values) 

# Filter the id dataset so each ID is only listed once
trawl_filter <- trawl %>%
  filter(type == "num")

# Join the filtered ID dataset with the widened subset
# For pres_abs column: if number is zero = absent (0), if number is nonzero = present
# For catch_100m column: number per 100m tow
# For biomass_100m column: g per 100m tow
trawl_tidy <- full_join(trawl_filter, trawl_wide, by = "sp_id") %>%
  select(-sp_id, -values, -type) %>%
  mutate(pres_abs = ifelse(num == 0, 0, 1),
         catch_100m = num/distance_m*100,
         biomass_100m = wt/distance_m*100)


# Fix some of the species names - changed or codes different from master list
trawl_tidy$species_name[trawl_tidy$species_name == "gerreidae"] <- "euc_spp"
trawl_tidy$species_name[trawl_tidy$species_name == "hyp_mee"] <- "hem_bar"
trawl_tidy$species_name[trawl_tidy$species_name == "atr_spa"] <- "ata_spa"
trawl_tidy$species_name[trawl_tidy$species_name == "mon_his"] <- "ste_his"
trawl_tidy$species_name[trawl_tidy$species_name == "gam_spp"] <- "gamb_spp"
trawl_tidy$species_name[trawl_tidy$species_name == "scianidae"] <- "sciaenidae"
trawl_tidy$species_name[trawl_tidy$species_name == "myc_spp"] <- "serranidae"
trawl_tidy$species_name[trawl_tidy$species_name == "sph_spp"] <- "sphy_spp"
trawl_tidy$species_name[trawl_tidy$species_name == "syg_flo"] <- "syn_flo"
trawl_tidy$species_name[trawl_tidy$species_name == "syg_spp"] <- "syn_spp"
trawl_tidy$species_name[trawl_tidy$species_name == "syo_foe"] <- "syn_foe"
trawl_tidy$species_name[trawl_tidy$species_name == "sph_spp2"] <- "spho_spp"
trawl_tidy$species_name[trawl_tidy$species_name == "lip_spp"] <- "lib_spp"
trawl_tidy$species_name[trawl_tidy$species_name == "shrimp"] <- "unid_shrimp"
trawl_tidy$species_name[trawl_tidy$species_name == "camarodonta"] <- "unid_sea_urchin"
trawl_tidy$species_name[trawl_tidy$species_name == "lut_gri_syn"] <- "lut_spp"




```


Use master list to create a common name identifier
```{r}
# Read in master sheet
master_sp_list <- read_csv("master_sp_list_sed.csv") %>% 
  select(field_id, common_name, species_name, family, order, common_group, sp_code)


# Tidy master list - need to get the 'sp_code' column in the same format as it is in trawl data
master_sp_tidy <- master_sp_list %>% 
  mutate(sp_code = str_to_lower(sp_code)) %>% 
  separate(sp_code,
           into = c("genus", "species", "extra"),
           sep = " ") %>% 
  unite(col = "sp_code",
        genus:extra,
        sep = "_",
        na.rm = TRUE)

# Create a vector with column named the same as in the trawl data
sp_names <- master_sp_tidy %>% 
  rename(scientific_name = species_name) %>% 
  rename(species_name = sp_code)


# Join columns from master to the trawl data
trawl_all <- left_join(trawl_tidy, sp_names, by = "species_name")

# Check NAs - want this to have ZERO! YAY!
trawl_na <- trawl_all %>% 
  filter(is.na(common_name)) 


```


## Narrow down the data a little bit - too hectic!

```{r}
# Remove some of the old dfs to make space in R's brain and mine
rm(master_sp_list, master_sp_tidy, sp_names, trawl, trawl_filter, trawl_na, trawl_test, trawl_wide, trawl_tidy)

# All that's left is trawl_all - aka our main dataframe based on everything done so far

# Should probably just focus on NC:
trawl_nc <- trawl_all %>% 
  filter(!is.na(site)) %>% 
  filter(site %in% c("Middle Marsh", "Core Sound", "Carrot Island"))

# Explore counts for each species to narrow down by number caught

# See which families are most represented
trawl_families <- trawl_nc %>% 
  group_by(family) %>% 
  summarize(total_number = sum(num, na.rm = TRUE)) %>% 
  arrange(-total_number) %>% 
  head(25)

# Counts from the top 35 represented families
trawl_topsp <- trawl_nc %>% 
  filter(family %in% trawl_counts$family) %>% 
  group_by(field_id) %>%
  summarize(total_number = sum(num, na.rm = TRUE)) %>% 
  arrange(-total_number) %>% 
  head(20)
  
```


# Filter by those top species: took 790k obs to 290k (just NC) obs to 30k obs

```{r}
trawl_subset <- trawl_nc %>% 
  filter(field_id %in% trawl_topsp$field_id)

write_csv(trawl_subset, "trawl_subset.csv")
```



